[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -P /dev/ttyUSB0 -b 57600"
# runner = "simavr -m atmega328p" 
# runner = "qemu-system-avr -nographic -machine uno -serial mon:stdio -bios" 

[unstable]
build-std = ["core"]
